### ISSUE TITLE
examples are using cpu as default

### ISSUE THREAD

**Issue by devilismyfriend** [jasonppy/VoiceCraft#20]
Hi!, thanks for releasing the weights, having some fun with the model so far!

I wanted to ask if there's a particular reason as to why the examples are currently set to use CPU instead of Cuda?

Thanks!

**Comment by signofthefour** [comment]
Hi!, I'm not the code's owner, I am just also curious about this repo. I think you are using the default code, which will use CPU if your machine does not have enough 8 GPUs. Because the author set the visible devices is 7:
`os.environ["CUDA_VISIBLE_DEVICES"]="7"`
And then he checks the availability of the GPU by this:
`device = "cuda" if torch.cuda.is_available() else "cpu"`
Let try to change 7 by 0.

**Comment by devilismyfriend** [comment]
he's still hard-coding the model to load on the CPU later on, so not sure if that would work.

**Comment by jasonppy** [comment]
Thanks for the feedback, will incorporate this into future changes.
If OOM, you can consider change `kvcache=0`, which will lead to slower inference, but doesn't consume as much memory. In my experience, 11GB GPU should work for 12 sec long generation.

**Comment by devilismyfriend** [comment]
after playing with it a bit, kvcache does reduce the vram usage, also reducing the batches, it will generally not work well on long tts from what I noticed but interesting anyway.
